services:
  - type: web
    name: find-home
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "8000"
