# Generated by Django 5.2.5 on 2025-09-12 10:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250910_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
